Early August 2024 updated builds 2
appveyor.yml - updated versions
appveyor.yml - in pg versions less than 16 use REL_xy_STABLE
appveyor.yml - in pg versions less than 16 use REL_xy_STABLE
appveyor.yml - Changed to Dave's token.  Made note of Dave's token and Andre's token
build.yml    - new REL_17 ubuntu build
schedule.yml - new REL_17 ubuntu build
install.md   - updated docs from R 4.3.1 to R 4.4.1
userguide.md - updated docs from R 4.3.1 to R 4.4.1
buildPLR.yml - added matrix id "matid" to Github Actions
               Needed to EASIER matrix entries with jobs
               Prevent Duplicated upload files from being created (see below)
buildPLR.yml - added matrix id matid to uploaded pg and plr file names
buildPLR.yml - added more pg REL_17 matrix entry items
buildPLR.yml - removed a duplicate job
buildPLR.yml - in pg versions less than 16 use REL_xy_STABLE
buildPLR.yml - Cache StrawberryPerl
               I tried and failed to use 64 perl because MSYS2 no longer has 32 bit perl
buildPLR.yml - upgraded Github Actions "uses: " to current versions EXCEPT upload-artifict
buildPLR.yml - updated mason version to meson-1.4.1
buildPLR.yml - fixed the broken URL to Windows2022-Readme.md
buildPLR.yml - pg10 case - Install Windows mingw Software
                but omit software - 1. perl 2. winpty (MSYS2 no longer has 32 software of these)
buildPLR.yml - replaced "meson test" "-v" paramenter with "-q --print-errorlogs"
                following the postgresql wiki -  wiki.postgresql.org/index.php?title=Meson&diff=39209&oldid=38340
buildPLR.yml - SOME pg17 jobs of type fail
                for any CONTRIB extension e.g. cube and plr
                and build type:
                R <v> PGsrc REL_17_<any> PGbin UCRT64 x64 windows-latest Debug R devel PGSRC PGSRCMETH SRCCTB true"
                (Later I need to figure out the COMMIT where these failures begin)
                Changed to have the workflow ignore in the workflow success/fail determination" using
                GithubActionsIgnoreFail: true" (RED X BY DESIGN)
buildPLR.yml - PLR builds (on MSYS2) of pg version 13 and lower fail
               ("pg version 13" did work 8 months ago. No code change has happened)
                Changed to have the workflow ignore in the workflow success/fail determination" using
                Currenly this matrix items are marked as "GithubActionsIgnoreFail: true"
                I may change these later. (or just drop the Matrix items).
                The case seems that MSYS2 and/or the Operating system is loosing support for the old.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -45,6 +45,72 @@ jobs:
         env:
           USE_PGXS: 1
 
+  REL_17_:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Echo site details
+        run: echo building master
+
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: checkout postgres
+        run: |
+          set -x -v -e
+          sudo apt-get update -qq
+          sudo apt-get install -qq r-base-dev acl bison flex libssl-dev
+          sudo R --version
+          sudo /etc/init.d/postgresql stop
+          sudo apt-get remove --purge postgresql\*
+          sudo rm -rf /etc/postgresql /var/lib/postgresql
+          export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_17_[0-9]')
+          if [ "${RET}" -gt "0" ]
+          then
+            echo -n "Release(s) are found.  Taking the last Release . . . "
+            export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_[0-9]' | tail -n 1)
+          else
+            echo "Release(s) are not found.  Trying Release Candidates."
+            export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_17_RC[0-9]')
+            if [ "${RET}" -gt "0" ]
+            then
+              echo -n "Release Candidate(s) are found.  Taking the last Release Candidate . . . "
+              export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_RC[0-9]' | tail -n 1)
+            else
+              echo "Release Candidate(s) are not found. Trying Betas."
+              export RET=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -c 'REL_17_BETA[0-9]')
+              if [ "${RET}" -gt "0" ]
+              then
+                echo -n "Beta(s) are found. Taking the last Beta . . . "
+                export GITTAG=$(git ls-remote --tags https://github.com/postgres/postgres.git | cut -c 52- | grep -e 'REL_17_BETA[0-9]' | tail -n 1)
+              else
+                echo "Beta(s) are not found."
+              fi
+            fi
+          fi
+          echo $GITTAG
+          git clone --branch $GITTAG --depth=1 https://github.com/postgres/postgres.git
+          pushd postgres
+          ./configure
+          make
+          sudo make install
+          export PATH=/usr/local/pgsql/bin:$PATH
+          initdb -D data
+          pg_ctl -D data -l logfile start
+          popd
+
+      - name: Script
+        run: |
+          set -x -v -e
+          export USE_PGXS=1
+          export PATH=/usr/local/pgsql/bin:$PATH
+          SHLIB_LINK=-lgcov PG_CPPFLAGS="-fprofile-arcs -ftest-coverage -O0" make
+          # USE_PGXS=1 is not required in Travis, and it is required in Github Actions
+          sudo USE_PGXS=1 PATH=/usr/local/pgsql/bin:$PATH make install
+          psql --version
+          make installcheck || (cat regression.diffs && false)
+        env:
+          USE_PGXS: 1
+
   build:
     runs-on: ubuntu-latest
     env:
@@ -52,14 +118,15 @@ jobs:
     strategy:
       matrix:
         include:
-          # SEEN SEP 2023
+          # SEEN JUL 2024
           # Ubuntu 22.04	ubuntu-latest
           # https://github.com/actions/runner-images
           # jammy (22.04, LTS)
           # https://wiki.postgresql.org/wiki/Apt
           # https://apt.postgresql.org/pub/repos/apt/dists/
-          # 16/ - 14-Sep-2023 12:35  
           # https://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/
+          # Source: postgresql-??
+          # https://apt.postgresql.org/pub/repos/apt/dists/jammy-pgdg/main/binary-amd64/Packages
           - pg: 16
           - pg: 15
           - pg: 14
@@ -72,7 +139,7 @@ jobs:
         run: echo PG $PG
 
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Before Script
         run: |
